name: Test

on: [push, pull_request]

jobs:
  test:
    name: test (${{ matrix.python.id }},${{ matrix.sage.id }})
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        python:
          - { id: "python3.9", version: "3.9" }
      fail-fast: false

    steps:
    - name: Cache
      id: cache-packages
      uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/cache-linux
        key: cache-packages-v2.2

    - name: Cache apt
      id: cache-apt
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/
        key: ${{ runner.os }}-apt-get-
        restore-keys: |
          ${{ runner.os }}-apt-get-

    - name: Cache pip
      id: cache-pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python.version }}
        architecture: x64
    - name: Update package lists of apt
      run: |
        sudo apt update
        sudo apt upgrade -y
    - name: Install GNU GMP3
      run: |
        sudo apt install -y libgmp3-dev
    - name: Install GNU MPC
      run: |
        sudo apt install -y libmpc-dev
    - name: Install SageMath
      run: |
        sudo apt install sagemath
    - name: Install python dependencies
      run: |
        pip install wheel
        pip install -r "requirements.txt"
    - name: Run tests
      run: |
        ./RsaCtfTool.py --tests
